const FETCH_DATA = "FETCH_DATA";
const LOADING_DATA = "LOADING_DATA";
const SUCCESS_DATA = "SUCCESS_DATA";
const ERROR_DATA = "ERROR_DATA";

export { FETCH_DATA, LOADING_DATA, SUCCESS_DATA, ERROR_DATA };
